spring:
   datasource:
      url: jdbc:mysql://192.168.2.198:3306/weeklyplan?useSSL=false&useOldAliasMetadataBehavior=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF8
      username: root
      password: Report@123
      driverClassName : com.mysql.jdbc.Driver
      thymeleaf:
      prefix: classpath:/main/
      suffix: .html
      encoding: UTF-8     
mybatis:
   mapperLocations: classpath:com/boot/mapper/mysql/**/*.xml
   typeAliasesPackage: cn.boot.domain
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
   level:
      root: info
server:
   port: 9080
db:
   schema: weeklyplan.